---
title: "Figure 1"
author: "Gosia Nowicka"
date: "29 Apr 2015"
output: 
  html_document:
    toc: true
---

```{r setup, echo = FALSE}
opts_knit$set(root.dir = "/home/Shared/data/array/Microarray_Edwin")
opts_chunk$set(message=FALSE, warning = FALSE, cache = TRUE, size="small", tidy=TRUE, tidy.opts=list(blank=FALSE, width.cutoff=70), dev = "pdf", cache.path = '/home/Shared/data/array/Microarray_Edwin/Plots_Figure1_cache/', fig.path = '/home/Shared/data/array/Microarray_Edwin/Plots_Figure1_figure/', fig.width = 5, fig.height = 5)
options(width=100)
```


# Load data

Load targets table with information about samples.

```{r targets}
targets.org <- read.table(file.path("metadata", "targets.xls"), header = TRUE, sep = "\t", comment.char = "", as.is = TRUE)

targets.org

```

Load Affy CEL data using `oligo` package. Plot the distributions of raw probe expression in all samples.

```{r CEL}
library(oligo)
library(pd.mogene.2.0.st)

ff <- as.character(targets.org$FileName)

x <- oligo::read.celfiles(filenames = ff)

```


# Normalize data with RMA method

```{r RMA}
eset.org <- oligo::rma(x) 

```



# Leukemia vs. control 


```{r Samps_controlAll}
####### Keep all controls and leukemia samples
keepSAMPS <- targets.org$ExperimentShort != "afterTreatment" & targets.org$labels != "control_HeLa"

eset <- eset.org[, keepSAMPS]
targets <- targets.org[keepSAMPS, ]

```


## MDS plot


```{r MDS_controls_All}
library(limma)
labels <- paste0(ifelse(is.na(targets$ctrlRep), "", paste0(targets$ctrlRep, " ")), targets$labels)

mds <- plotMDS(eset, top=1000, col = targets$colors, labels = labels, cex = 1, xlim = c(-2, 3), ylim = c(-2, 3), las = 1, cex.axis = 1, cex.lab = 1)

```



```{r Samps_control}
####### Keep only the CD4, CD8 and CD4CD8 controls and leukemia samples
keepSAMPS <- targets.org$ExperimentShort != "afterTreatment" & targets.org$labels != "control_HeLa" & targets.org$labels != "control_wholeBoneMarrow"

eset <- eset.org[, keepSAMPS]
targets <- targets.org[keepSAMPS, ]

```


## MDS plot


```{r MDS_controls}
library(limma)
labels <- paste0(ifelse(is.na(targets$ctrlRep), "", paste0(targets$ctrlRep, " ")), targets$labels)

mds <- plotMDS(eset, top=1000, col = targets$colors, labels = labels, cex = 1, xlim = c(-2, 3), ylim = c(-2, 3), las = 1, cex.axis = 1, cex.lab = 1)

```


## Heatmaps


```{r Heatmaps_controls_niche_binding, fig.width = 5, fig.height = 5}

library(pheatmap)

### sort samples by groups
ord <- order(targets$groups)
targets <- targets[ord, ]
eset <- eset[ ,ord]

expr <- data.frame(exprs(eset))
### normalize expression per gene
exprNorm <- t(scale(t(expr), center = TRUE, scale = TRUE))

### load list of genes of interest

intrGenes <- read.table("Gene_Sets/niche_interaction_genes_v3_niche_binding.csv", header = TRUE, sep = ",")
intrProbes <- as.character(intrGenes$ProbesetID)

dataHeat <- exprNorm[intrProbes, ]

annotation_col <- targets[, "groups", drop = FALSE]
rownames(annotation_col) <- colnames(dataHeat)

cols <- unique(targets$colors)
names(cols) <- unique(targets$group)
  
annotation_colors = list(groups = cols)

labels_row <- strsplit2(intrGenes$GeneSymbol, " /// ")[, 1]


### Plot of expression scaled per gene 
pheatmap(dataHeat, color = colorRamps::matlab.like(100), cluster_cols = FALSE, annotation_col = annotation_col, annotation_colors = annotation_colors, labels_col = targets$groups, labels_row = labels_row, annotation_legend = FALSE, fontsize_row = 6, fontsize_col = 6, gaps_col = cumsum(table(targets$groups)), breaks =  seq(from = -3, to = 3, length.out = 101), legend_breaks = seq(from = -3, to = 3, by = 2), fontsize = 6)

```



```{r Heatmaps_controls_niche_formation, fig.width = 5, fig.height = 5}


### load list of genes of interest

intrGenes <- read.table("Gene_Sets/niche_interaction_genes_v3_niche_formation.csv", header = TRUE, sep = ",")
intrProbes <- as.character(intrGenes$ProbesetID)

dataHeat <- exprNorm[intrProbes, ]

annotation_col <- targets[, "groups", drop = FALSE]
rownames(annotation_col) <- colnames(dataHeat)

cols <- unique(targets$colors)
names(cols) <- unique(targets$group)

annotation_colors = list(groups = cols)

labels_row <- strsplit2(intrGenes$GeneSymbol, " /// ")[, 1]

### Plot of expression scaled per gene
pheatmap(dataHeat, color = colorRamps::matlab.like(100), cluster_cols = FALSE, annotation_col = annotation_col, annotation_colors = annotation_colors, labels_col = targets$groups, labels_row = labels_row, annotation_legend = FALSE, fontsize_row = 6, fontsize_col = 6, gaps_col = cumsum(table(targets$groups)), breaks =  seq(from = -3, to = 3, length.out = 101), legend_breaks = seq(from = -3, to = 3, by = 2), fontsize = 6)

```




# After vs. before treatment 

```{r Samps_afterTreatment}
####### Keep only the control and leukemia samples

keepSAMPS <- targets.org$ExperimentShort == "afterTreatment" | targets.org$ExperimentShort == "leukemia"

eset <- eset.org[, keepSAMPS]
targets <- targets.org[keepSAMPS, ]


```


## MDS plot


```{r MDS_afterTreatment}
library(limma)
labels <- targets$labels

mds <- plotMDS(eset, top=1000, col = targets$colors, labels = labels, cex = 1, xlim = c(-2, 3), ylim = c(-2, 3), las = 1, cex.axis = 1, cex.lab = 1)

```


## Heatmaps


```{r Heatmaps_afterTreatment, fig.width = 5, fig.height = 5}

library(pheatmap)

### sort samples by groups
ord <- order(targets$groups)
targets <- targets[ord, ]
eset <- eset[ ,ord]

expr <- data.frame(exprs(eset))
### normalize expression per gene
exprNorm <- t(scale(t(expr), center = TRUE, scale = TRUE))

### load list of genes of interest

intrGenes <- read.table("Gene_Sets/niche_interaction_genes_v3_niche_binding.csv", header = TRUE, sep = ",")
intrProbes <- as.character(intrGenes$ProbesetID)

dataHeat <- exprNorm[intrProbes, ]

annotation_col <- targets[, "groups", drop = FALSE]
rownames(annotation_col) <- colnames(dataHeat)

cols <- unique(targets$colors)
names(cols) <- unique(targets$group)
  
annotation_colors = list(groups = cols)

labels_row <- strsplit2(intrGenes$GeneSymbol, " /// ")[, 1]


### Plot of expression scaled per gene 
pheatmap(dataHeat, color = colorRamps::matlab.like(100), cluster_cols = FALSE, annotation_col = annotation_col, annotation_colors = annotation_colors, labels_col = targets$groups, labels_row = labels_row, annotation_legend = FALSE, fontsize_row = 6, fontsize_col = 6, gaps_col = cumsum(table(targets$groups)), breaks =  seq(from = -3, to = 3, length.out = 101), legend_breaks = seq(from = -3, to = 3, by = 2), fontsize = 6)

```



```{r Heatmaps_afterTreatment_niche_formation, fig.width = 5, fig.height = 5}


### load list of genes of interest

intrGenes <- read.table("Gene_Sets/niche_interaction_genes_v3_niche_formation.csv", header = TRUE, sep = ",")
intrProbes <- as.character(intrGenes$ProbesetID)

dataHeat <- exprNorm[intrProbes, ]

annotation_col <- targets[, "groups", drop = FALSE]
rownames(annotation_col) <- colnames(dataHeat)

cols <- unique(targets$colors)
names(cols) <- unique(targets$group)

annotation_colors = list(groups = cols)

labels_row <- strsplit2(intrGenes$GeneSymbol, " /// ")[, 1]

### Plot of expression scaled per gene
pheatmap(dataHeat, color = colorRamps::matlab.like(100), cluster_cols = FALSE, annotation_col = annotation_col, annotation_colors = annotation_colors, labels_col = targets$groups, labels_row = labels_row, annotation_legend = FALSE, fontsize_row = 6, fontsize_col = 6, gaps_col = cumsum(table(targets$groups)), breaks =  seq(from = -3, to = 3, length.out = 101), legend_breaks = seq(from = -3, to = 3, by = 2), fontsize = 6)
```







```{r}
sessionInfo()
```








